server {
    listen 443 ssl;
    server_name sehatin.rizcasaur.us;

    # Define the root directory where your website files are located
    root /var/www/sehatin;
    index index.html;

    # Enable proxy cache
    proxy_cache_key "$scheme://$host$request_uri";

    # Default file to serve
    location / {
        try_files $uri $uri/ =404;  # Try to serve requested file, otherwise return 404

        # Enable Redis cache for static files
        proxy_cache my_cache;
        proxy_cache_valid 200 1h;
        proxy_cache_use_stale error timeout updating;
        add_header X-Cache-Status $upstream_cache_status;
    }

    ssl_certificate /root/rizcasaur.us/certs/origin.pem;
    ssl_certificate_key /root/rizcasaur.us/certs/privatekey.pem;
    ssl_trusted_certificate /etc/ssl/certs/origin_ca_rsa_root.pem;

    ssl_protocols TLSv1.2 TLSv1.3;  # Ensure only secure protocols are used
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256';  # Strong ciphers
    ssl_prefer_server_ciphers on;

    # SSL Session Cache and Timeout (optional, but recommended for performance)
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1h;

    # Optional: DH parameters (for forward secrecy)
    # ssl_dhparam /etc/nginx/ssl-dhparams.pem;

    # Logging
    access_log /var/log/nginx/sehatin_rizcasaur_us_access.log;
    error_log /var/log/nginx/sehatin_rizcasaur_us_error.log;


}

server {
    listen 80;
    server_name sehatin.rizcasaur.us;

    if ($host = sehatin.rizcasaur.us) {
        return 301 https://$host$request_uri;  # Redirect HTTP to HTTPS
    }

    # Return a 404 error if the HTTP request is not redirected properly
    return 404;
}