name: Deploy Static Website to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy static files to /var/www/medapp
        run: |
          # Copy the root HTML file (index.html)
          sudo rm -f /var/www/medapp/*.html
          sudo cp -v ./index.html /var/www/medapp/
          sudo cp -v ./profile.html /var/www/medapp/
          sudo cp -v ./manifest.json /var/www/medapp/
          sudo cp -v ./users.json /var/www/medapp/
          sudo cp -v ./service-worker.js /var/www/medapp/
          sudo cp -v ./monitoring.html /var/www/medapp/
          sudo cp -v ./fallback.html /var/www/medapp/
          sudo cp -v ./digital.html /var/www/medapp/
          sudo cp -v ./telemed.html /var/www/medapp/
          sudo cp -v ./docprofile.html /var/www/medapp/
          sudo cp -v ./login.html /var/www/medapp/
          sudo cp -v ./home.html /var/www/medapp/

          # Copy the entire public folder (for favicon.ico and other assets)
          sudo cp -rv ./assets /var/www/medapp/

          # Copy the entire src folder (assets, css, js, etc.)
          sudo chown -R :www-data /var/www/medapp
          sudo chmod -R 775 /var/www/medapp
          sudo ls -l /var/www/medapp/
          sudo tree /var/www/medapp/